services:
  filebrowser:
    container_name: filebrowser
    image: gtstef/filebrowser:1.2.4-stable-slim
    networks:
      - traefik_traefik-network
      - db_db-network
      - filebrowser-network
    volumes:
      - /docker-volumes/filebrowser/config:/home/filebrowser/data
      - /docker-volumes/filebrowser/files:/files
    ports:
      - "8900:80"
    restart: unless-stopped
    environment:
      - "FILEBROWSER_CONFIG=/home/filebrowser/data/config.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik-network"
      - "traefik.http.routers.drive.rule=Host(`drive.wvl.app`)"
      - "traefik.http.routers.drive.entrypoints=websecure"
      - "traefik.http.routers.drive.tls.certresolver=le"

networks:
  filebrowser-network:
  db_db-network:
    external: true
  traefik_traefik-network:
    external: true
