services:
  databasus:
    container_name: databasus
    restart: unless-stopped
    image: databasus/databasus:latest
    ports:
      - "4005:4005"
    volumes:
      - docker-volumes/backup-server/databasus/data:/databasus-data
