services:
  db:
    image: postgres:15
    security_opt:
      - "no-new-privileges:true"
    restart: unless-stopped
    environment:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: kitchenowl
    env_file:
      - .env
    volumes:
      - /docker-volumes/kitchen-owl/db:/var/lib/postgresql/data
    networks:
      - kitchen-owl-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  kitchen-owl:
    container_name: kitchen-owl
    restart: unless-stopped
    image: tombursch/kitchenowl:v0.7.8
    networks:
#      - db_db-network
      - kitchen-owl-network
      - traefik_traefik-network
    ports:
      - "3002:8080"
    environment:
      FRONT_URL: https://keuken.wvl.app
      DISABLE_USERNAME_PASSWORD_LOGIN: true
      OIDC_ISSUER: https://auth.wvl.app
      OIDC_CLIENT_ID: 373524057661898755
      OIDC_NAME: Home
      DB_DRIVER: postgresql
      DB_PORT: 5432
      DB_HOST: db
      DB_NAME: kitchenowl
      DB_USER: kitchenowl
    env_file:
      - .env
    volumes:
      - /docker-volumes/kitchen-owl/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik-network"
      - "traefik.http.routers.keuken.rule=Host(`keuken.wvl.app`)"
      - "traefik.http.routers.keuken.entrypoints=websecure"
      - "traefik.http.routers.keuken.tls.certresolver=le"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          pids: 99

volumes:
  kitchenowl_data:

networks:
  kitchen-owl-network:
#  db_db-network:
#    external: true
  traefik_traefik-network:
    external: true
