services:
  zitadel:
    restart: "unless-stopped"
    networks:
      - "reverse-proxy_reverse-proxy-network"
      - "db_db-network"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: start-from-init --config /zitadel-config.yaml --config /run/secrets/zitadel_secrets --steps /zitadel-init-steps.yaml --masterkey "${ZITADEL_MASTERKEY}" --tlsMode disabled
    ports:
      - "8080:8080"
    volumes:
      - /docker-volumes/zitadel/init-steps.yaml:/zitadel-init-steps.yaml:ro
      - /docker-volumes/zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro
    secrets:
      - zitadel_secrets

secrets:
  zitadel_secrets:
    file: /docker-volumes/secrets/zitadel_secrets.yaml

networks:
  db_db-network:
    external: true
  reverse-proxy_reverse-proxy-network:
    external: true