name: reverse-proxy
services:
  reverse-proxy:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - reverse-proxy-network
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=reverse-proxy_reverse-proxy-network"
      # Entry-points & Automated Redirects
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.asDefault=true"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      # Certificate resolvers
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=wvl@wvl.app"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`wvl.app`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=le"

      - "traefik.http.routers.baby-redirect.rule=Host(`baby.wvl.app`)"
      - "traefik.http.routers.baby-redirect.entrypoints=websecure"
      - "traefik.http.routers.baby-redirect.tls=true"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.regex=^https://baby.wvl.app/(.*)"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.replacement=https://babeeworld.com/birthlists/871?access_token=0TGRQ226TCN7TZO"
      - "traefik.http.middlewares.baby-redir-mw.redirectregex.permanent=true"
      - "traefik.http.routers.baby-redirect.middlewares=baby-redir-mw"
      - "traefik.http.routers.baby-redirect.tls.certresolver=le"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/docker-volumes/traefik/letsencrypt:/letsencrypt"

networks:
  reverse-proxy-network:
    driver: bridge
