log:
  level: "DEBUG"

api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: reverse_proxy-proxy-network

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      httpChallenge:
        entryPoint: "web"
      email: "wvl@wvl.app"
      storage: "/letsencrypt/acme.json"