# volume-fsn1-1 -- 100 GB in fsn1. Moving from bumba to mindy, 2026-09-18.
#
# It carried bumba's postgres until that morning, reached through a SYMLINK
# rather than a mount:
#
#   /docker-volumes/db/data -> /mnt/HC_Volume_103225027/db/data/
#
# PGDATA now lives on bumba's root disk. Verify by the container's own mount
# table, never by the symlink -- docker binds by device at container start, so
# replacing the symlink under a running container changes nothing, and that is
# exactly how the migration looked finished while still writing to this volume:
#
#   grep " /data/postgres " /proc/$(docker inspect -f '{{.State.Pid}}' database-db-1)/mountinfo
#   -> 8:1  /dev/sda1   root disk, correct
#   -> 8:16 /dev/sdb    this volume, migration NOT in effect
#
# What is still on it: a frozen copy of that postgres data directory, and an
# immich directory last written 2026-03-16 whose library is an empty skeleton
# and whose database is superseded by mindy's (448 MB, 14,817 assets).
#
# It moves rather than being deleted because ../../../docs/data-architecture.md
# wants a volume on the host that runs immich and filebrowser -- which is mindy
# -- for photos, audio and documents. A detached volume is billed in full, so
# leaving it parked on bumba costs the same as using it.
#
# NOTE ON SIZE: a Hetzner volume can only GROW. 100 GB now; the data-architecture
# target is 150 GB. Growing is a one-way door, so size it against measured usage.
resource "hcloud_volume" "data" {
  # NAMING: servers are Studio 100 characters (bumba, mindy, samson, plop),
  # storage boxes are Disney princesses (snow-white), volumes are Disney SIDE
  # characters. `volume-fsn1-1` was Hetzner's default and carried no meaning.
  #
  # Rafiki keeps the record -- he paints the history and remembers who everyone
  # is -- which is the job this volume is being moved to mindy to do.
  #
  # Renaming is safe for anything mounting it: /dev/disk/by-id/scsi-0HC_Volume_*
  # and /mnt/HC_Volume_* are built from the volume ID (103225027), not the name.
  # The plan must show an IN-PLACE update. A replacement would mean the provider
  # treats name as ForceNew, and prevent_destroy below would stop it -- safely,
  # but stop it.
  name     = "rafiki"
  location = "fsn1"
  size     = 100

  delete_protection = true
  automount         = null
  format            = null
  labels            = {}

  lifecycle {
    # Holds the only remaining copy of bumba's pre-migration postgres data
    # directory, which is the rollback for that move. Keep until the root-disk
    # database has proven itself.
    prevent_destroy = true
  }
}

# Was `bumba_db`. Renamed because it is no longer bumba's, and no longer a
# database volume.
moved {
  from = hcloud_volume.bumba_db
  to   = hcloud_volume.data
}

# The attachment as its own resource, rather than `server_id` on the volume.
#
# Two reasons. `server_id` is optional+computed, so it cannot express "detached"
# -- removing it leaves the volume attached and tofu reports no change. And the
# provider docs say server_id is not allowed alongside `location`; both were set
# here only because the resource was generated by import.
#
# Deleting this resource detaches. Changing server_id replaces it, which IS a
# detach followed by an attach -- which is what moves the volume between hosts.
#
# UNMOUNT ON BUMBA FIRST. Detaching a mounted ext4 filesystem is an unclean
# disconnect, and what is on it is the rollback for the postgres migration:
#
#   ssh root@<bumba> 'umount /mnt/HC_Volume_103225027 && sed -i "/HC_Volume_103225027/d" /etc/fstab'
#
# automount is false: attaching gives mindy a /dev/sdX, nothing more. Where it
# gets mounted and what goes on it is the data-architecture project, not this
# change, and a half-configured automount is worse than an obvious manual step.
resource "hcloud_volume_attachment" "data" {
  volume_id = hcloud_volume.data.id
  server_id = hcloud_server.mindy.id
  automount = false
}
