name: it-tools
services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - it-tools-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: "60s"
      timeout: "30s"
      retries: "5"
      start_period: "20s"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99

networks:
  it-tools-network: