#!/bin/sh
# Generates the ed25519 sync identities backrest needs, into secrets.auto.tfvars.
#
# WHY THESE ARE SUPPLIED RATHER THAN GENERATED BY TOFU.
#
# Backrest makes its own identity when the config has none -- see
# PopulateRequiredFields in internal/config/config.go -- and then WRITES IT BACK
# into config.json. modules/services/backrest keeps config.json in the container
# layer rather than a bind mount, deliberately, so that a UI edit cannot outlive
# an apply. The cost is that a generated identity does not survive either: every
# container replacement mints a new keyid, and a peer that declared the old one
# breaks on every apply.
#
# Tofu cannot generate them either. The identity is a RAW 32-byte ed25519 seed
# in unpadded base64, and the keyid is base64url(sha256(raw public key)).
# `tls_private_key` only emits PEM/DER, HCL has no way to slice the seed out of
# that, and `sha256()` hashes a UTF-8 string rather than raw bytes.
#
# So they are generated once, here, and pinned. Same category as
# TF_VAR_zitadel_masterkey: a value tofu carries but does not create.
#
# The values never reach a terminal -- they are appended straight to
# secrets.auto.tfvars, which is gitignored. This repo is public.
set -eu

cd "$(dirname "$0")"
OUT=secrets.auto.tfvars

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

# A 32-byte ed25519 seed lives in the last 32 bytes of the PKCS#8 DER, and the
# raw public key in the last 32 of the SubjectPublicKeyInfo DER. Both encodings
# are fixed-length for ed25519, which is what makes `tail -c 32` safe here.
#
# base64 -w0 then `tr -d '='`: Backrest decodes with RawStdEncoding, which
# rejects padding.
emit() { # emit <tfvars variable name>
  var="$1"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT

  openssl genpkey -algorithm ed25519 -out "$tmp/k.pem" 2>/dev/null
  openssl pkey -in "$tmp/k.pem" -outform DER 2>/dev/null | tail -c 32 > "$tmp/seed.bin"
  openssl pkey -in "$tmp/k.pem" -pubout -outform DER 2>/dev/null | tail -c 32 > "$tmp/pub.bin"

  priv="$(base64 -w0 < "$tmp/seed.bin" | tr -d '=')"
  pub="$(base64 -w0 < "$tmp/pub.bin" | tr -d '=')"
  keyid="ed25519.$(openssl dgst -sha256 -binary < "$tmp/pub.bin" | base64 -w0 | tr '+/' '-_' | tr -d '=')"

  [ "${#priv}" -eq 43 ] || { echo "unexpected seed length ${#priv}, want 43" >&2; exit 1; }
  [ "${#pub}" -eq 43 ] || { echo "unexpected pubkey length ${#pub}, want 43" >&2; exit 1; }

  {
    printf '\n%s = {\n' "$var"
    printf '  keyid = "%s"\n' "$keyid"
    printf '  priv  = "%s"\n' "$priv"
    printf '  pub   = "%s"\n' "$pub"
    printf '}\n'
  } >> "$OUT"

  rm -rf "$tmp"; trap - EXIT
  printf '  %-32s %s\n' "$var" "$keyid"
}

touch "$OUT"

for var in backrest_identity_mindy backrest_identity_samson; do
  if grep -q "^${var} *=" "$OUT" 2>/dev/null; then
    printf '  %-32s [already present -- leaving it alone]\n' "$var"
    continue
  fi
  emit "$var"
done

cat <<'MSG'

Written to secrets.auto.tfvars. Only the keyids are shown above; they are not
secret -- they are the public fingerprints each peer uses to recognise the other.

REGENERATING ONE BREAKS THE PAIRING until the other side's apply catches up,
because each instance declares the other's keyid. Delete both entries and re-run
if you ever need to rotate, then apply once.
MSG
