# 9443 is portainer, which tofu does not manage. plex uses
# network_mode = "host", so it publishes nothing through docker -- 32400 and
# friends are taken but cannot appear here.
locals {
  samson_ports = {
    databasus = 4005
    backrest  = 9898
  }
}

check "samson_unique_ports" {
  assert {
    condition     = length(values(local.samson_ports)) == length(distinct(values(local.samson_ports)))
    error_message = "two services in samson.tf are published on the same host port"
  }
}

module "databasus" {
  source = "./modules/services/databasus"

  providers = {
    docker = docker.samson
  }

  host_port = local.samson_ports.databasus
}

module "plex" {
  source = "./modules/services/plex"

  providers = {
    docker = docker.samson
  }
}


module "backrest_samson" {
  source = "./modules/services/backrest"

  providers = {
    docker = docker.samson
  }

  instance     = "samson"
  tailscale_ip = var.samson_addr
  config_path  = "/docker-volumes/backrest"

  cpus = "4.0"


  backup = [
    module.plex.backup,
    module.databasus.backup,

    # audio-archive has no owning module: it lives on samson but is served by
    # filebrowser on mindy. Declared here rather than pretending otherwise.
    { mounts = { "audio-archive" = "/export/audio-archive" } },
  ]

  repository_password = random_password.backrest_repository.result
  repo_path           = "restic"
  storage_box_id      = module.hetzner.storage_box_id
  sftp_host           = module.hetzner.storage_box_host

  # Through bumba. samson cannot authenticate to the Storage Box directly.
  connect_host = var.bumba_addr
  connect_port = module.storage_box_proxy.listen_port

  gatus_token    = module.gatus.backrest_push_token
  gatus_base_url = module.gatus.external_endpoint_base_url
  gatus_endpoint = "backups_backrest-samson"

  # THE CLIENT of the sync pair. Pushes its operations up to mindy so both
  # appear in one dashboard; samson's own UI keeps working regardless.
  #
  # Plain http over the tailnet -- the handshake is signed with the identities
  # above, so the transport is not what authenticates it.
  sync_identity = var.backrest_identity_samson
  sync_known_hosts = var.backrest_identity_mindy == null ? [] : [{
    instance_id  = "mindy"
    keyid        = var.backrest_identity_mindy.keyid
    instance_url = "http://${var.mindy_addr}:9898"
    scopes       = ["*"]
  }]

  port = local.samson_ports.backrest
}

# --- values ---------------------------------------------------------------

locals {
}

# --- inputs ---------------------------------------------------------------

variable "samson_addr" {
  type        = string
  description = "samson's TAILNET address. Reached as root over SSH for the docker provider, like the other two hosts."
}

# samson's half of the sync pair, so its backup progress shows up in mindy's
# dashboard as well as its own. null disables sync on both sides.
#
# Generated by ./backrest-identity.sh. The reasoning for why these are supplied
# rather than generated by tofu is on backrest_identity_mindy in mindy.tf, and at
# length in that script.
variable "backrest_identity_samson" {
  type = object({
    keyid = string
    priv  = string
    pub   = string
  })
  default   = null
  sensitive = true
}

# --- outputs --------------------------------------------------------------


output "backrest_samson_password" {
  value     = module.backrest_samson.ui_password
  sensitive = true
}
