services:
  homeassistant:
    restart: unless-stopped
    image: "home-assistant/home-assistant:v2026.6.4"
    environment:
      TZ: Europe/Brussels
    ports:
      - "8123:8123"
    networks:
      - home-assistant-network
    volumes:
      - /docker-volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99
          cpus: 6
          memory: 8gb

  matterjs-server:
    container_name: matterjs-server
    restart: unless-stopped
    image: ghcr.io/matter-js/matterjs-server:1.1.5
    read_only: true
    network_mode: host
    volumes:
      - /docker-volumes/homeassistant/matterjs-server:/data"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          pids: 99
          cpus: 6
          memory: 8gb

networks:
  home-assistant-network: