services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "wvl.app,homepage.wvl.app,100.127.106.121:3001"
      PUID: 1000
      PGID: 1000
    volumes:
      - /docker-volumes/homepage/config:/app/config
      - /docker-volumes/homepage/icons:/app/public/icons
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_traefik-network"
      - "traefik.http.routers.homepage.rule=Host(`homepage.wvl.app`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=le"
    networks:
      - homepage-network
      - traefik_traefik-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          pids: 99

networks:
  homepage-network:
  traefik_traefik-network:
    external: true
